---
title: "R Data Types"
author: "Wylie Hampson"
date: "8/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Create a vector

```{r}
vec_1 <- c(2, 5, 9, 10, 8, 12, 1, 0)
vec_1
class(vec_1)
typeof(vec_1)

# get the third element
vec_1_e3 <- vec_1[3]
vec_1_e3

# get the first element
vec_1_e1 <- vec_1[1]
vec_1_e1

# get elements 5 to 7
vec_1_e5to7 <- vec_1[5:7]
vec_1_e5to7

vec_1_char <- as.character(vec_1)
vec_1_char
```

```{r}
vec_2 <- c(town = "Santa Barbara", location = "Rincon", swell = "south")
vec_2
class(vec_2)

typeof(vec_2)

vec_2[2]

vec_2["location"]

# What is the length of vec_2?
length(vec_2)

vec_2_e2 <- vec_2[2]
vec_2_e2

```

## Create a dateframe

```{r}
df_1 <- data.frame(region = c("A", "B", "A", "D"),
                   species = c("otter", "great white", "sea lion", "gray whale"),
                   count = c(12, 2, 36, 6))
df_1

# Return the class of df_1
class(df_1)

# Return the class of just the species column
class(df_1$species)

# Find the maximum value of the count() column
max_count <- max(df_1$count)
max_count
```

